CREATE INDEX idx_customer_code ON m_customer(c_customer_code);
CREATE INDEX idx_customer_name ON m_customer(c_name);
CREATE INDEX idx_customer_phone ON m_customer_phone(cp_phone);
CREATE INDEX idx_job_no ON t_job(j_job_no);
CREATE INDEX idx_job_status ON t_job(j_job_status);
CREATE INDEX idx_job_appointment ON t_job(j_appointment_start, j_appointment_end);
CREATE INDEX idx_job_technician ON t_job(id_m_user);
CREATE INDEX idx_job_customer ON t_job(id_m_customer);
CREATE INDEX idx_job_public_token ON t_job(j_public_token);
CREATE INDEX idx_job_original ON t_job(id_t_original_job);
CREATE INDEX idx_job_item_job ON t_job_item(id_t_job);
CREATE INDEX idx_job_activity_job_date ON t_job_activity(id_t_job, ja_activity_date DESC);
CREATE INDEX idx_attachment_job ON t_job_attachment(id_t_job);
CREATE INDEX idx_payment_no ON t_payment(p_payment_no);
CREATE INDEX idx_payment_job_date ON t_payment(id_t_job, p_payment_date DESC);
CREATE INDEX idx_refund_job_date ON t_refund(id_t_job, rf_refund_date DESC);
CREATE INDEX idx_product_code ON m_product(p_product_code);
CREATE INDEX idx_stock_product_date ON t_stock_transaction(id_m_product, create_date DESC);
CREATE INDEX idx_stock_date ON t_stock_transaction(create_date DESC);
CREATE INDEX idx_notification_user_unread ON t_notification(id_m_user, n_is_read, create_date DESC);
